"""Data models for governance checks and coaching sessions."""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class ComplianceStatus(str, Enum):
    PASS = "pass"
    FAIL = "fail"
    WARNING = "warning"
    NOT_APPLICABLE = "not_applicable"


class CoachingPriority(str, Enum):
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class ComplianceItem(BaseModel):
    """A single governance / compliance check result."""

    rule_id: str
    rule_name: str
    status: ComplianceStatus
    description: str = Field(
        default="", description="Explanation of what was checked"
    )
    finding: str = Field(
        default="",
        description="What was found in the conversation regarding this rule",
    )
    remediation_hint: str = Field(
        default="", description="Guidance on how to address a failure or warning"
    )


class GovernanceCheck(BaseModel):
    """Aggregated governance evaluation for a case."""

    case_id: str
    agent_id: str
    compliance_items: List[ComplianceItem] = Field(default_factory=list)
    overall_compliant: bool = True
    critical_violations: List[str] = Field(
        default_factory=list,
        description="IDs of rules that were critically violated",
    )
    summary: str = Field(
        default="", description="Narrative summary of the governance check"
    )

    @property
    def failed_items(self) -> List[ComplianceItem]:
        return [
            i
            for i in self.compliance_items
            if i.status in (ComplianceStatus.FAIL, ComplianceStatus.WARNING)
        ]


class CoachingRecommendation(BaseModel):
    """A single actionable coaching recommendation for the agent."""

    priority: CoachingPriority
    title: str
    description: str
    action_steps: List[str] = Field(
        default_factory=list,
        description="Concrete steps the agent can take to implement this recommendation",
    )
    related_dimension: Optional[str] = Field(
        default=None,
        description="Quality dimension or governance rule this recommendation addresses",
    )
    example_script: Optional[str] = Field(
        default=None,
        description="Optional example phrasing the agent can use",
    )


class CoachingSession(BaseModel):
    """A complete coaching session generated by the Agent Coach."""

    session_id: str
    case_id: str
    agent_id: str
    agent_name: str = ""
    generated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    recommendations: List[CoachingRecommendation] = Field(default_factory=list)
    opening_message: str = Field(
        default="",
        description="Personalised opening message to the agent",
    )
    closing_message: str = Field(
        default="",
        description="Motivational closing message",
    )
    overall_quality_score: float = Field(default=0.0)
    compliance_passed: bool = True

    @property
    def critical_recommendations(self) -> List[CoachingRecommendation]:
        return [
            r for r in self.recommendations if r.priority == CoachingPriority.CRITICAL
        ]

    @property
    def high_priority_recommendations(self) -> List[CoachingRecommendation]:
        return [
            r for r in self.recommendations if r.priority == CoachingPriority.HIGH
        ]
